modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "aeqc"
version = "${version}"
displayName = "AE2 QoL Client"
displayURL="" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="Debris" #optional
description = '''
Add qol features to ae2
'''

[[mixins]]
config = "aeqc.mixins.json"

[[dependencies.aeqc]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aeqc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aeqc]]
modId = "mafglib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aeqc]]
modId = "jei"
type = "required"
versionRange = "[19.27.0.340,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aeqc]]
modId = "ae2"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
